// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RHS.Persistence;

#nullable disable

namespace RHS.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111131439_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RHS.Domain.Resume.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<byte[]>("DemoGif")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("demo_gif");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_title");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_url");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("ix_projects_resume_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("RHS.Domain.Resume.ResumeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GitHubLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_hub_link");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("introduction");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LinkedInLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linked_in_link");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("RHS.Domain.Resume.Entities.ProjectEntity", b =>
                {
                    b.HasOne("RHS.Domain.Resume.ResumeEntity", "ResumeEntity")
                        .WithMany("Projects")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_resumes_resume_id");

                    b.Navigation("ResumeEntity");
                });

            modelBuilder.Entity("RHS.Domain.Resume.ResumeEntity", b =>
                {
                    b.OwnsOne("RHS.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ResumeEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("ResumeEntityId");

                            b1.ToTable("resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeEntityId")
                                .HasConstraintName("fk_resumes_resumes_id");
                        });

                    b.OwnsOne("RHS.Domain.Resume.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("ResumeEntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("full_name_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("full_name_last_name");

                            b1.HasKey("ResumeEntityId");

                            b1.ToTable("resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeEntityId")
                                .HasConstraintName("fk_resumes_resumes_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("RHS.Domain.Resume.ResumeEntity", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
